name = "hono-firestore-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# ضع هنا بيانات Firebase الخاصة بك
FIREBASE_PROJECT_ID = "your-project-id"
FIREBASE_API_KEY = "your-web-api-key"